/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jes
 */
public class CommandsToolGUI extends javax.swing.JFrame {
    
    String binSelected;
    final String DESCRIBE=" --describe";
    final String FROM_BEGINNING=" --from-beginning";
    int xMouse, yMouse;

    /**
     * Creates new form CommandsToolGUI
     */
    public CommandsToolGUI() {
        initComponents();
        scaleImage();
        elementsOnStart();
    }
    
    public void scaleImage(){
        ImageIcon icon = new ImageIcon("C:\\Users\\Jes\\Documents\\NetBeansProjects\\KafkaApacheCommandsTool\\src\\img\\fondo.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jLabel1.setIcon(scaledIcon);
    }
    
    public void elementsOnStart(){
        topicjTextField.setVisible(false);
        bServerjTextField.setVisible(false);
        partitionsjTextField.setVisible(false);
        repFactjTextField.setVisible(false);
        describejCheckBox.setVisible(false);
        buildjButton.setVisible(false);
        beginningjCheckBox1.setVisible(false);
        jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        topicjTextField = new javax.swing.JTextField();
        bServerjTextField = new javax.swing.JTextField();
        partitionsjTextField = new javax.swing.JTextField();
        repFactjTextField = new javax.swing.JTextField();
        describejCheckBox = new javax.swing.JCheckBox();
        beginningjCheckBox1 = new javax.swing.JCheckBox();
        buildjButton = new javax.swing.JButton();
        startZookeeperjLabel = new javax.swing.JLabel();
        binZookeeperjLabel = new javax.swing.JLabel();
        startKafkajLabel = new javax.swing.JLabel();
        binKafkajLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 580));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(java.awt.Color.white);
        jScrollPane1.setForeground(java.awt.Color.black);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(java.awt.Color.white);
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(java.awt.Color.black);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 320, 190));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Command Tool");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 28)); // NOI18N
        jLabel3.setForeground(java.awt.Color.lightGray);
        jLabel3.setText("Apache Kafka");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jComboBox1.setBackground(java.awt.Color.white);
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setForeground(java.awt.Color.black);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona bin/", "bin/kafka-topics.sh", "bin/kafka-console-producer.sh", "bin/kafka-console-consumer.sh" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 270, 30));

        topicjTextField.setBackground(java.awt.Color.white);
        topicjTextField.setForeground(java.awt.Color.gray);
        topicjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topicjTextFieldMousePressed(evt);
            }
        });
        jPanel1.add(topicjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 570, -1));

        bServerjTextField.setBackground(new java.awt.Color(255, 255, 255));
        bServerjTextField.setForeground(java.awt.Color.gray);
        bServerjTextField.setText("--bootstrap-server");
        bServerjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bServerjTextFieldMousePressed(evt);
            }
        });
        jPanel1.add(bServerjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 570, -1));

        partitionsjTextField.setBackground(java.awt.Color.white);
        partitionsjTextField.setForeground(java.awt.Color.gray);
        partitionsjTextField.setText("--partitions");
        partitionsjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                partitionsjTextFieldMousePressed(evt);
            }
        });
        jPanel1.add(partitionsjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 570, -1));

        repFactjTextField.setBackground(java.awt.Color.white);
        repFactjTextField.setForeground(java.awt.Color.gray);
        repFactjTextField.setText("--replication-factor");
        repFactjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                repFactjTextFieldMousePressed(evt);
            }
        });
        jPanel1.add(repFactjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 570, -1));

        describejCheckBox.setBackground(java.awt.Color.white);
        describejCheckBox.setForeground(java.awt.Color.gray);
        describejCheckBox.setText("--describe");
        describejCheckBox.setOpaque(true);
        describejCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                describejCheckBoxMouseClicked(evt);
            }
        });
        jPanel1.add(describejCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 90, -1));

        beginningjCheckBox1.setBackground(java.awt.Color.white);
        beginningjCheckBox1.setForeground(java.awt.Color.gray);
        beginningjCheckBox1.setText("--from-beginning");
        beginningjCheckBox1.setOpaque(true);
        jPanel1.add(beginningjCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 150, -1));

        buildjButton.setBackground(java.awt.Color.black);
        buildjButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buildjButton.setForeground(java.awt.Color.white);
        buildjButton.setText("Build");
        buildjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buildjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildjButtonMouseClicked(evt);
            }
        });
        jPanel1.add(buildjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 90, 50));

        startZookeeperjLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        startZookeeperjLabel.setForeground(java.awt.Color.white);
        startZookeeperjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startZookeeperjLabel.setText("# Start the ZooKeeper service");
        jPanel1.add(startZookeeperjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 30));

        binZookeeperjLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        binZookeeperjLabel.setForeground(java.awt.Color.white);
        binZookeeperjLabel.setText("bin/zookeeper-server-start.sh config/zookeeper.properties");
        jPanel1.add(binZookeeperjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 420, -1));

        startKafkajLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        startKafkajLabel.setForeground(java.awt.Color.white);
        startKafkajLabel.setText("# Start the Kafka broker service");
        jPanel1.add(startKafkajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        binKafkajLabel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        binKafkajLabel.setForeground(java.awt.Color.white);
        binKafkajLabel.setText("bin/kafka-server-start.sh config/server.properties");
        jPanel1.add(binKafkajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        jPanel2.setBackground(java.awt.Color.black);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 677, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 707, 30));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 710, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        binSelected = (String)jComboBox1.getSelectedItem();
        if(binSelected == "Selecciona bin/"){
            elementsOnStart();
            startZookeeperjLabel.setVisible(true);
            binZookeeperjLabel.setVisible(true);
            startKafkajLabel.setVisible(true);
            binKafkajLabel.setVisible(true);
            jScrollPane1.setVisible(false);
        }
        if(binSelected == "bin/kafka-topics.sh"){
            startZookeeperjLabel.setVisible(false);
            binZookeeperjLabel.setVisible(false);
            startKafkajLabel.setVisible(false);
            binKafkajLabel.setVisible(false);
            jScrollPane1.setVisible(false);
            beginningjCheckBox1.setVisible(false);
            
            topicjTextField.setVisible(true);
            bServerjTextField.setVisible(true);
            partitionsjTextField.setVisible(true);
            repFactjTextField.setVisible(true);
            describejCheckBox.setVisible(true);
            buildjButton.setVisible(true);
            System.out.println("primera opcion");
        }
        if(binSelected == "bin/kafka-console-producer.sh"){
            topicjTextField.setVisible(true);
            bServerjTextField.setVisible(true);
            buildjButton.setVisible(true);
            
            startZookeeperjLabel.setVisible(false);
            binZookeeperjLabel.setVisible(false);
            startKafkajLabel.setVisible(false);
            binKafkajLabel.setVisible(false);
            partitionsjTextField.setVisible(false);
            repFactjTextField.setVisible(false);
            describejCheckBox.setVisible(false);
            beginningjCheckBox1.setVisible(false);
            jScrollPane1.setVisible(false);
        }
        if(binSelected == "bin/kafka-console-consumer.sh"){
            topicjTextField.setVisible(true);
            bServerjTextField.setVisible(true);
            beginningjCheckBox1.setVisible(true);
            buildjButton.setVisible(true);
            
            startZookeeperjLabel.setVisible(false);
            binZookeeperjLabel.setVisible(false);
            startKafkajLabel.setVisible(false);
            binKafkajLabel.setVisible(false);
            partitionsjTextField.setVisible(false);
            repFactjTextField.setVisible(false);
            describejCheckBox.setVisible(false);
            jScrollPane1.setVisible(false);
        }
        if(binSelected == "bin/kafka-configs.sh"){
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void buildjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildjButtonMouseClicked
        // TODO add your handling code here:
        if(binSelected == "bin/kafka-topics.sh"){
            String topic = topicjTextField.getText();
            String bServer = bServerjTextField.getText();
            String partitions = partitionsjTextField.getText();
            String repFact = repFactjTextField.getText();
            
            if(describejCheckBox.isSelected()){
                if(!topic.equals("--topic")
                        && !bServer.equals("--bootstrap-server")){
                    if(!topic.isEmpty()
                            &&!bServer.isEmpty()){
                        topicjTextField.setSize(250,topicjTextField.getHeight());
                        bServerjTextField.setSize(250,topicjTextField.getHeight());
                        partitionsjTextField.setVisible(false);
                        repFactjTextField.setVisible(false);
                        jScrollPane1.setVisible(true);
                        jTextArea1.setText("");
                        jTextArea1.setText("bin/kafka-topics.sh --topic "+topic+" --bootstrap-server "+bServer+DESCRIBE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Debes llenar todos los campos","Campos Obligatorios",2);
                }
                
            }if(!describejCheckBox.isSelected()){
                if(!topic.equals("--topic")
                        &&!bServer.equals("--bootstrap-server")
                        &&!partitions.equals("--partitions")
                        &&!repFact.equals("--replication-factor")){
                    if(!topic.isEmpty()
                            &&!bServer.isEmpty()
                            &&!partitions.isEmpty()
                            &&!repFact.isEmpty()){
                        topicjTextField.setSize(250,topicjTextField.getHeight());
                        bServerjTextField.setSize(250,topicjTextField.getHeight());
                        partitionsjTextField.setSize(250,topicjTextField.getHeight());
                        repFactjTextField.setSize(250,topicjTextField.getHeight());
                        jScrollPane1.setVisible(true);
                        jTextArea1.setText("");
                        jTextArea1.setText("bin/kafka-topics.sh --create --topic "+topic+" --bootstrap-server "+bServer+" --partitions "+partitions+" --replication-factor "+repFact);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Debes llenar todos los campos","Campos Obligatorios",2);
                }
            }
            
        }
        if(binSelected == "bin/kafka-console-producer.sh"){
            String topic = topicjTextField.getText();
            String bServer = bServerjTextField.getText();
            
            if(!topic.equals("--topic")&&!bServer.equals("--bootstrap-server")){
                if(!topic.isEmpty()&&!bServer.isEmpty()){
                    topicjTextField.setSize(250,topicjTextField.getHeight());
                    bServerjTextField.setSize(250,topicjTextField.getHeight());
                    jScrollPane1.setVisible(true);
                    jTextArea1.setText("");
                    jTextArea1.setText("bin/kafka-console-producer.sh --topic "+topic+" --bootstrap-server "+bServer);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Debes llenar todos los campos","Campos Obligatorios",2);
                jScrollPane1.setVisible(false);
                topicjTextField.setSize(570,topicjTextField.getHeight());
                bServerjTextField.setSize(570,topicjTextField.getHeight());
            }
            
        }
        if(binSelected == "bin/kafka-console-consumer.sh"){
            String topic = topicjTextField.getText();
            String bServer = bServerjTextField.getText();
            
            if(!topic.equals("--topic")&&!bServer.equals("--bootstrap-server")){
                if(!topic.isEmpty()&&!bServer.isEmpty()){
                    if(beginningjCheckBox1.isSelected()){
                        topicjTextField.setSize(250,topicjTextField.getHeight());
                        bServerjTextField.setSize(250,topicjTextField.getHeight());
                        jScrollPane1.setVisible(true);
                        jTextArea1.setText("");
                        jTextArea1.setText("bin/kafka-console-consumer.sh --topic "+topic+" --bootstrap-server "+bServer+FROM_BEGINNING);
                    }else{
                        topicjTextField.setSize(250,topicjTextField.getHeight());
                        bServerjTextField.setSize(250,topicjTextField.getHeight());
                        jScrollPane1.setVisible(true);
                        jTextArea1.setText("");
                        jTextArea1.setText("bin/kafka-console-consumer.sh --topic "+topic+" --bootstrap-server "+bServer);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null,"Debes llenar todos los campos","Campos Obligatorios",2);
                jScrollPane1.setVisible(false);
                topicjTextField.setSize(570,topicjTextField.getHeight());
                bServerjTextField.setSize(570,topicjTextField.getHeight());
            }
        }
    }//GEN-LAST:event_buildjButtonMouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        jScrollPane1.setVisible(false);
        if(topicjTextField.getText().equals("--topic")){
            topicjTextField.setText("");
            topicjTextField.setForeground(Color.BLACK);
        }if(topicjTextField.getText().isEmpty()){
            topicjTextField.setText("--topic");
            topicjTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void topicjTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topicjTextFieldMousePressed
        // TODO add your handling code here:
        if(topicjTextField.getText().equals("--topic")){
            topicjTextField.setText("");
            topicjTextField.setForeground(Color.BLACK);
        }
        if(bServerjTextField.getText().isEmpty()
                ||partitionsjTextField.getText().isEmpty()
                ||repFactjTextField.getText().isEmpty()){
            bServerjTextField.setText("--bootstrap-server");
            bServerjTextField.setForeground(Color.GRAY);
            partitionsjTextField.setText("--partitions");
            partitionsjTextField.setForeground(Color.GRAY);
            repFactjTextField.setText("--replication-factor");
            repFactjTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_topicjTextFieldMousePressed

    private void bServerjTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bServerjTextFieldMousePressed
        // TODO add your handling code here:
        if(bServerjTextField.getText().equals("--bootstrap-server")){
            bServerjTextField.setText("");
            bServerjTextField.setForeground(Color.BLACK);
        }
        if(topicjTextField.getText().isEmpty()
                ||partitionsjTextField.getText().isEmpty()
                ||repFactjTextField.getText().isEmpty()){
            topicjTextField.setText("--topic");
            topicjTextField.setForeground(Color.GRAY);
            partitionsjTextField.setText("--partitions");
            partitionsjTextField.setForeground(Color.GRAY);
            repFactjTextField.setText("--replication-factor");
            repFactjTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_bServerjTextFieldMousePressed

    private void partitionsjTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partitionsjTextFieldMousePressed
        // TODO add your handling code here:
        if(partitionsjTextField.getText().equals("--partitions")){
            partitionsjTextField.setText("");
            partitionsjTextField.setForeground(Color.BLACK);
        }
        if(topicjTextField.getText().isEmpty()
                ||bServerjTextField.getText().isEmpty()
                ||repFactjTextField.getText().isEmpty()){
            topicjTextField.setText("--topic");
            topicjTextField.setForeground(Color.GRAY);
            bServerjTextField.setText("--bootstrap-server");
            bServerjTextField.setForeground(Color.GRAY);
            repFactjTextField.setText("--replication-factor");
            repFactjTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_partitionsjTextFieldMousePressed

    private void repFactjTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repFactjTextFieldMousePressed
        // TODO add your handling code here:
        if(repFactjTextField.getText().equals("--replication-factor")){
            repFactjTextField.setText("");
            repFactjTextField.setForeground(Color.BLACK);
        }
        if(topicjTextField.getText().isEmpty()
                ||bServerjTextField.getText().isEmpty()
                ||partitionsjTextField.getText().isEmpty()){
            topicjTextField.setText("--topic");
            topicjTextField.setForeground(Color.GRAY);
            bServerjTextField.setText("--bootstrap-server");
            bServerjTextField.setForeground(Color.GRAY);
            partitionsjTextField.setText("--partitions");
            partitionsjTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_repFactjTextFieldMousePressed

    private void describejCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_describejCheckBoxMouseClicked
        // TODO add your handling code here:
        if(describejCheckBox.isSelected()){
            describejCheckBox.setForeground(Color.BLACK);
            partitionsjTextField.setVisible(false);
            repFactjTextField.setVisible(false);
        }else{
            describejCheckBox.setForeground(Color.GRAY);
            partitionsjTextField.setVisible(true);
            repFactjTextField.setVisible(true);
        }
    }//GEN-LAST:event_describejCheckBoxMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommandsToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommandsToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommandsToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommandsToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommandsToolGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bServerjTextField;
    private javax.swing.JCheckBox beginningjCheckBox1;
    private javax.swing.JLabel binKafkajLabel;
    private javax.swing.JLabel binZookeeperjLabel;
    private javax.swing.JButton buildjButton;
    private javax.swing.JCheckBox describejCheckBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField partitionsjTextField;
    private javax.swing.JTextField repFactjTextField;
    private javax.swing.JLabel startKafkajLabel;
    private javax.swing.JLabel startZookeeperjLabel;
    private javax.swing.JTextField topicjTextField;
    // End of variables declaration//GEN-END:variables
}
